<?php

//------------------------------------------------------------------------------
// Core hooks

module_load_include('inc', 'coral', 'classes/node');


/**
 * Implementation of hook_init().
 */
function coral_page_init() {
  $module_path = drupal_get_path('module', 'coral_page');

	coral_include(array(
		'classes/nodes'
	));
}


/**
 * Return a list of the Coral node classes.
 */
function coral_page_coral_classes_alter($type, &$class_map) {
  if ($type == 'node') {	
  	$class_map[CoralPageNode::type()] = 'CoralPageNode';
	}
}
