<?php

coral_include(array(
  'classes/nodes'
), 'inc', array('module' => 'coral_page'));

//------------------------------------------------------------------------------
// Core hooks

/**
 * Return a list of the Coral node classes.
 */
function coral_page_coral_classes_alter($type, &$class_map) {
  if ($type == 'node') {	
  	$class_map[CoralPageNode::type()] = 'CoralPageNode';
	}
}
