<?php

coral_include(array(
  'classes/nodes'
), 'inc', array('module' => 'coral_image_slide'));

//------------------------------------------------------------------------------
// Core hooks

/**
 * Return a list of the Coral node classes.
 */
function coral_image_slide_coral_classes_alter($type, &$class_map) {
  if ($type == 'node') {	
  	$class_map[CoralImageSlideNode::type()] = 'CoralImageSlideNode';
	}
}
