<?php

coral_include(array(
  'classes/nodes'
), 'inc', array('module' => 'coral_media_slide'));

//------------------------------------------------------------------------------
// Core hooks

/**
 * Return a list of the Coral node classes.
 */
function coral_media_slide_coral_classes_alter($type, &$class_map) {
  if ($type == 'node') {	
  	$class_map[CoralMediaSlideNode::type()] = 'CoralMediaSlideNode';
	}
}
