<?php

/**
 * Implements hook_entity_property_info_alter().
 */
function coral_solr_fields_entity_property_info_alter(&$info) {
  $info['node']['properties']['user_image'] = array(
    'type' => 'text',
    'label' => t('User image'),
    'sanitized' => TRUE,
    'getter callback' => 'coral_solr_fields_user_image_getter_callback',
  );
}

/**
 * Getter callback for user image.
 */
function coral_solr_fields_user_image_getter_callback($item) {
  $user = $item->uid;
  $user = user_load($user);
  
  $uri = 'public://coraltechiconlg.png'; // default image
  
  // See also function mosaic_compile_default_user_image($user, $image_style, $title) {
  if (is_object($user) && $user->uid) {
    if (isset($user->picture->uri)) {
      $uri = $user->picture->uri;
    }
  }
  
  return $uri;
}
